// <auto-generated />
using System;
using InterviewTask.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220825193459_of")]
    partial class of
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InterviewTask.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 8, 25, 23, 34, 59, 290, DateTimeKind.Local).AddTicks(7128),
                            Name = "Dev"
                        });
                });

            modelBuilder.Entity("InterviewTask.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2022, 8, 25, 23, 34, 59, 290, DateTimeKind.Local).AddTicks(7091),
                            CreateDate = new DateTime(2022, 8, 25, 23, 34, 59, 290, DateTimeKind.Local).AddTicks(7098),
                            DepartmentId = 1,
                            Name = "Khalid",
                            Surname = "Rajabov"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2022, 8, 25, 23, 34, 59, 290, DateTimeKind.Local).AddTicks(7116),
                            CreateDate = new DateTime(2022, 8, 25, 23, 34, 59, 290, DateTimeKind.Local).AddTicks(7117),
                            DepartmentId = 1,
                            Name = "Felix",
                            Surname = "Paw"
                        });
                });

            modelBuilder.Entity("InterviewTask.Models.Employee", b =>
                {
                    b.HasOne("InterviewTask.Models.Department", "Departmen")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departmen");
                });

            modelBuilder.Entity("InterviewTask.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
